spring:
  application:
    name: servicio-zuul-server
server:
 port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    store:
      service-id: service-store
      path: /api/tienda/**
    termo:
      service-id: service-termo
      path: /api/thermo/**
    usuarios:
      service-id: service-usuarios
      path: /api/us/**
    oauth:
      service-id: service-oauth
      path: /api/security/**
      sensitive-headers: Cookie,Set-Cookie
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
            