server:
  port: 8000
spring:
  application:
    name: service-termos
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      